#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# get colors from Xresources
function get () {
  xrdb -query | grep "$1" | awk '{print $2}' | tail -n1
}

bspc config border_width 02
bspc config window_gap 00
bspc config top_padding 20
bspc config bottom_padding 00

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config split_ratio 0.50
bspc config click_to_focus button1
bspc config focus_follows_pointer false

# set colors based off current x11 colors
bspc config normal_border_color "$(get color0)"
bspc config active_border_color "$(get color6)"
bspc config focused_border_color "$(get color2)"
bspc config presel_feedback_color "$(get color2)"
